### ISSUE TITLE
Build-time failures hang heavy-test build jobs

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelicaLibraryTesting#135]
Checking the following test reports:

https://libraries.openmodelica.org/branches/heavy_tests/ScalableTestSuite_NB/ScalableTestSuite_NB.html
https://libraries.openmodelica.org/branches/heavy_tests/ScalableTestSuite_OB/ScalableTestSuite_OB.html
https://libraries.openmodelica.org/branches/heavy_tests/LargeTestSuite_NB/LargeTestSuite_NB.html
https://libraries.openmodelica.org/branches/newInst-newBackend/ScalableTestGrids_noopt/ScalableTestGrids_noopt.html

it is apparent that timeouts during C-compile time and run time are reported correctly and take place after the specified BuildModel time limit and Simulation time limit. For some reason, timeouts during code generation seem not to be reported correctly to the Python script, which then duly waits two times the BuildModel timeout + the Simulation time limit + 25 extra seconds before failing, without any report at all.

This makes the testing time much longer, because of the unnecessary very long waiting times, and prevents displaying proper diagnostic logs.

@adrpo can you please figure out what's wrong here and correct it?

Thanks!

**Comment by adrpo** [comment]
It seems the thread is just waiting for something:

```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f0a4f15e3ea in __GI___wait4 (pid=-1, stat_loc=0x7ffe7c6bba8c, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30      ../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
(gdb) info threads
  Id   Target Id                                Frame
* 1    Thread 0x7f0a4f071740 (LWP 2639862) "sh" 0x00007f0a4f15e3ea in __GI___wait4 (pid=-1, stat_loc=0x7ffe7c6bba8c, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
(gdb) bt
#0  0x00007f0a4f15e3ea in __GI___wait4 (pid=-1, stat_loc=0x7ffe7c6bba8c, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
#1  0x00005559beefbea4 in ?? ()
#2  0x00005559beefc11a in ?? ()
#3  0x00005559bef093c0 in ?? ()
#4  0x00005559bef02c00 in ?? ()
#5  0x00005559bef02c00 in ?? ()
#6  0x00005559bef066c2 in ?? ()
#7  0x00005559beefad36 in ?? ()
#8  0x00007f0a4f09dd90 in __libc_start_call_main (main=main@entry=0x5559beefaae0, argc=argc@entry=3, argv=argv@entry=0x7ffe7c6bbf88) at ../sysdeps/nptl/libc_start_call_main.h:58
#9  0x00007f0a4f09de40 in __libc_start_main_impl (main=0x5559beefaae0, argc=3, argv=0x7ffe7c6bbf88, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe7c6bbf78)
    at ../csu/libc-start.c:392
#10 0x00005559beefaf15 in ?? ()

```

**Comment by adrpo** [comment]
Let see if PR #151 works.

**Comment by adrpo** [comment]
#154 should fix it.

**Comment by casella** [comment]
We'll see as soon as the [old-libs](https://test.openmodelica.org/jenkins/job/LibraryTesting/job/LibraryTest/8599/) test is done.
