### ISSUE TITLE
Nightly tests broken

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelicaLibraryTesting#67]
`python` can't be found when running test.py

```python
try:
  subprocess.check_output(["python", "testmodel.py", "--help"], stderr=subprocess.STDOUT)
```

from https://github.com/OpenModelica/OpenModelicaLibraryTesting/blame/master/test.py#L151C3-L151C64.

See https://test.openmodelica.org/jenkins/job/LibraryTesting/job/LibraryTest/7548/console

```
libraries.openmodelica.org/branches/cpp/ --libraries=/home/hudson/saved_omc/libraries/.openmodelica/libraries/ --jobs=0 configs/conf.json
Traceback (most recent call last):
  File "/var/lib/jenkins1/ws/OpenModelicaLibraryTestingWork/OpenModelicaLibraryTesting/./test.py", line 151, in <module>
    subprocess.check_output(["python", "testmodel.py", "--help"], stderr=subprocess.STDOUT)
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python'
```

**Comment by AnHeuermann** [comment]
Python can have all sorts of funny names. On the Ubuntu machines it's probably `python3`. We can use

```python
import sys
pythonExec = sys.executable
```

to get the full name of the interpreter running the script.
